src/main/scripts/ctl/functions.xml

Fixed function boolean-as-integer to work with string values

---

src/site/markdown/index.md

Added hint about missing service parameter

---

src/main/scripts/ctl/basic_elements.xml

Added encoding of format parameter

---

src/main/scripts/ctl/getfeatureinfo.xml

Getfeatureinfo-each-queryable-layer

---

pom.xml
src/assembly/deps.xml

Enable compiling of the file and creation of the dep artifact (needed for REST API)

---

src/main/scripts/ctl/getmap.xml

Use specific parser depending on content-type of response to prevent exception

---

src/main/config/config.xml

Fixed the issue of ctl test case view.

---

src/main/scripts/ctl/basic.xml
src/main/scripts/ctl/main-auto.xml
src/main/scripts/ctl/main.xml
src/main/scripts/ctl/queryable.xml
src/main/scripts/ctl/raster_elevation.xml
src/main/scripts/ctl/recommendations.xml
src/main/scripts/ctl/time.xml
src/main/scripts/ctl/vector_elevation.xml

Configured conformance classes

---

jenkinsfiles/test/Jenkinsfile
pom.xml
src/test/resources/soapui/ets-wms13-soapui-project.xml

Created SoapUI tests and integrated with the maven.

---

src/main/java/org/opengis/cite/wms13/TestRunArguments.java
src/main/java/org/opengis/cite/wms13/WMS13.java
src/main/javadoc/overview.html
src/main/resources/org/opengis/cite/wms13/test-run-props.xml

Updated the description of the parameter basic in REST API doc.

---

jenkinsfiles/test/Jenkinsfile
pom.xml
src/test/resources/soapui/ets-wms13-soapui-project.xml

Updated SoapUI project and removed the version from URI. 

---

pom.xml
src/main/java/org/opengis/cite/wms13/CtlController.java

Updated the maven dependency in pom.xml

---

pom.xml
src/main/config/config.xml
src/test/resources/soapui/ets-wms13-soapui-project.xml

Fixed the REST URI issue and updated the SoapUI project to support new URI prefix.

---

pom.xml

Updated TE version to 5.4.

---

src/test/resources/soapui/ets-wms13-soapui-project.xml

Reference: https://github.com/opengeospatial/teamengine/issues/462#issuecomment-799301806

Added header for soapui test.

---

src/main/scripts/ctl/basic.xml
src/main/scripts/ctl/queryable.xml

Updated XPath to get layers using name.

---

src/main/scripts/ctl/getmap.xml
src/site/resources/wms-1_3_0-ats.html

Added new test case named as getmap:no-version.

---

src/main/scripts/ctl/getmap.xml

Fixed xpath issue for getmap:invalid-format test.

---

pom.xml
src/main/scripts/ctl/basic.xml
src/site/markdown/index.md

Update the scripts to remove cite: prefix from the Layer Names

---

src/main/scripts/ctl/basic.xml
src/main/scripts/ctl/queryable.xml

Fix failures caused by non mandatory cite prefix in layer name

---

src/main/scripts/ctl/getmap.xml

Closes #112

---

src/main/scripts/ctl/getmap.xml

Closes #98

---

src/main/scripts/ctl/time.xml

Closes #113
